# Host: legendbits.shop.local -> /api = backend:8000, / = frontend:80
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop
  namespace: shop
spec:
  ingressClassName: nginx
  rules:
  - host: legendbits.shop.local
    http:
      paths:
      - backend:
          service:
            name: backend
            port:
              number: 8000
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
